jobs:
  update_release_draft:
    if: github.repository_owner == 'apache'
    name: Update Release Draft
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      id: prepare_release
      name: Update release body draft
      uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7
      with:
        disable-autolabeler: true
name: Release Drafter
on:
  repository_dispatch:
    types: trigger-ga___release-drafter.yml
